name: Build Qt App

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          bin-name: windows-x64

        - name: Linux x64
          os: ubuntu-22.04
          bin-name: linux-x64

        - name: Linux ARM64
          os: ubuntu-22.04-arm
          bin-name: linux-arm64

        - name: macOS
          os: macos-14
          bin-name: macos-arm

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.10.1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir ./build
          cd ./build
          cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S .. -B . -G Ninja

      - name: Build the app
        run: cmake --build ./build --config Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-build-${{ matrix.config.bin-name }}
          path: ./bin/**