name: Build Qt App

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  find-qt-ver:
    name: Find Qt version
    runs-on: ubuntu-latest
    outputs:
      qt_ver: ${{ steps.save_ver.outputs.qt_ver }}
      qt_ver_major: ${{ steps.save_ver.outputs.qt_ver_major }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Save Qt version
        id: save_ver
        shell: bash
        run: |
          if [ -f ./.github/workflows/qt/VERSION ]; then
            export QT_VER=$(cat ./.github/workflows/qt/VERSION)
            export QT_VER_MAJOR=$(echo $QT_VER | grep -oE '^[0-9]+')

            echo "::notice::----- Qt version: $QT_VER -----"
            echo "::notice::----- Qt major version: $QT_VER_MAJOR -----"

            echo "qt_ver=$QT_VER" >> $GITHUB_OUTPUT
            echo "qt_ver_major=$QT_VER_MAJOR" >> $GITHUB_OUTPUT
          else
            echo "::error::----- Could not locate .github/workflows/qt/VERSION -----"
            echo "::error::----- Please run the CMake configuration locally at least once."

            exit 1
          fi

  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          bin-name: windows-x64

        - name: Linux x64
          os: ubuntu-24.04
          bin-name: linux-x64

        - name: Linux ARM64
          os: ubuntu-24.04-arm
          bin-name: linux-arm64

        - name: macOS
          os: macos-14
          bin-name: macos-arm

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: ['find-qt-ver']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ needs.find-qt-ver.outputs.qt_ver }}
          cache: true

      - name: Configure CMake
        run: |
          mkdir ./build
          cd ./build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S .. -B . -G Ninja

      - name: Build the app
        run: cmake --build ./build --config Release

      - name: Install linuxdeployqt
        if: ${{ runner.os == 'Linux' }}
        uses: Fryy55/install-linuxdeployqt-action@main

      # platform specific packaging
      - name: Bundle Windows
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          $PROJECT_NAME = [System.IO.Path]::GetFileNameWithoutExtension((ls ./bin))
          echo "----- Packaging project $PROJECT_NAME -----"; echo " "
          windeployqt --release --compiler-runtime ./bin/$PROJECT_NAME.exe
          Compress-Archive -Path ./bin/* -DestinationPath ./$PROJECT_NAME-windows.zip

      - name: Bundle Linux
        if: ${{ runner.os == 'Linux' }}
        run: QT_SELECT=qt${{ needs.find-qt-ver.outputs.qt_ver_major }} linuxdeployqt ./bin/* -unsupported-allow-new-glibc -exclude-libs=libqsqlmimer


      - name: Bundle MacOS
        if: ${{ runner.os == 'MacOS' }}
        run: |
          cd ./bin
          macdeployqt ./*.app -dmg
          export DMG_OUT=$(echo ./*.dmg)
          mv ./$DMG_OUT ../$DMG_OUT


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-build-${{ matrix.config.bin-name }}
          path: |
            ./*.zip
            ./*.AppImage
            ./*.dmg