name: Build Qt App

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          bin-name: windows-x64

        - name: Linux x64
          os: ubuntu-22.04
          bin-name: linux-x64

        - name: Linux ARM64
          os: ubuntu-24.04-arm
          bin-name: linux-arm64

        - name: macOS
          os: macos-14
          bin-name: macos-arm

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.10.1
          cache: true

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          mkdir ./build
          cd ./build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S .. -B . -G Ninja

      - name: Build the app
        run: cmake --build ./build --config Release

      - name: Install linuxdeployqt
        if: ${{ runner.os == 'Linux' }}
        uses: miurahr/install-linuxdeployqt-action@v1.0.1

      # platform specific packaging
      - name: Bundle Windows
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |
          $PROJECT_NAME = [System.IO.Path]::GetFileNameWithoutExtension((ls ./bin))
          echo "----- Packaging project $PROJECT_NAME -----`n"
          windeployqt --release --compiler-runtime ./bin/$PROJECT_NAME.exe
          Compress-Archive -Path ./bin/* -DestinationPath ./$PROJECT_NAME-windows.zip

      - name: Bundle Linux
        if: ${{ runner.os == 'Linux' }}
        run: QT_SELECT=qt6 linuxdeployqt -appimage ./bin/*

      - name: Bundle MacOS
        if: ${{ runner.os == 'MacOS' }}
        run: |
          cd ./bin
          macdeployqt ./*.app -dmg
          export DMG_OUT=$(echo ./*.dmg)
          mv ./$DMG_OUT ../$DMG_OUT


      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-build-${{ matrix.config.bin-name }}
          path: |
            ./*.zip
            ./*.AppImage
            ./*.dmg